server {
  listen 80;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name localhost;

  ssl_certificate /etc/nginx/ssl/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/key.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:DHE-RSA-AES128-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!RC4:!MD5:!SSLv2:!SSLv3';
  ssl_prefer_server_ciphers on;

  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 1d;
  ssl_stapling on;
  ssl_stapling_verify on;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass https://flowjudge.api:8081;
    proxy_ssl_name localhost;
    proxy_set_header Host localhost;
    proxy_set_header X-Forwarded-Proto https;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html =404;
  }
}
